-- 创建公安数据库
drop DATABASE if exists `BIDDB`;
CREATE DATABASE `BIDDB` CHARACTER SET 'utf8'  COLLATE 'utf8_general_ci';

use BIDDB;

CREATE TABLE VendorNotice (
  FID INTEGER(11) NOT NULL,
  FNAME VARCHAR(50) DEFAULT NULL,
  FID_CARD VARCHAR(50) DEFAULT NULL,
  FSEX INTEGER(11) DEFAULT NULL,
  FADDR VARCHAR(100) DEFAULT NULL,
  PIC_FILE VARCHAR(100) DEFAULT NULL,
  FSTATUS INTEGER(11) DEFAULT 0,
  PRIMARY KEY (FID) COMMENT ''
);

